version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/eCommerceDs?schema=public
      - JWT_KEY=tu_clave_secreta_muy_segura
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ecommerce-network

  db:
    image: postgres:15-alpine
    container_name: ecommerce-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eCommerceDs
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eCommerceDs"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  ecommerce-network:
    driver: bridge

# Volumes for data persistence
volumes:
  postgres-data: