FROM postgres:15-alpine

# Create directory for initialization scripts
RUN mkdir -p /docker-entrypoint-initdb.d

# Copy the initialization scripts
COPY init-db/01-init.sql /docker-entrypoint-initdb.d/01-init.sql

# Change the owner of the files to postgres
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d/
